### ISSUE TITLE
Possible bug when using with a Bidirectional layer

### ISSUE THREAD

**Issue by frozaken** [xuxingya/tf2crf#6]
Hello, i was trying to implement https://www.aclweb.org/anthology/Y18-1061.pdf, and thought it should be as simple as 
`pred_crf = Bidirectional(CRF(), merge_mode="sum")(pred)` 
however this yields the following
` Traceback (most recent call last):
  File "oscar/tensorflow/traingraph.py", line 28, in <module>
    w2v_size=50)
  File "C:\Users\Marcus\Source\Repos\roger\OsCaR\oscar\tensorflow\fullgraphmodel.py", line 56, in get_model
    pred_crf = Bidirectional(crf, merge_mode="sum")(pred)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tensorflow_core\python\keras\layers\wrappers.py", line 426, in __init__
    self.forward_layer = self._recreate_layer_from_config(layer)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tensorflow_core\python\keras\layers\wrappers.py", line 507, in _recreate_layer_from_config
    return layer.__class__.from_config(config)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 519, in from_config
    return cls(**config)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tf2crf\crf.py", line 30, in __init__
    super(CRF, self).__init__(**kwargs)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 186, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)

  File "C:\Users\Marcus\Anaconda3\envs\roger\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 718, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'output_dim')`

**Comment by frozaken** [comment]
Using version 0.1.13

**Comment by frozaken** [comment]
I implemented this manually instead
